### ISSUE TITLE
BamProcessing.wdl, Float contamination = read_float(stdout())

### ISSUE THREAD

**Issue by ad2n15** [broadinstitute/warp#1059]
Hi team,

I got this error related to checkcontamination.contamination task that fail to read the output !!!!!!!!!!!!!. Althou, the output was generated as norma. It loos this is a timeout problem, I am using Slurm. I try to add Maxretries: 3, but I can see no tries and the error happen sometimes.

[INFO] [08/05/2023 16:07:21.133] [cromwell-system-akka.dispatchers.engine-dispatcher-26] [akka://cromwell-system/user/SingleWorkflowRunnerActor/WorkflowManagerActor] WorkflowManagerActor: Workflow 2bfcc03f-928f-48bf-ad4d-ca8816dd6be0 failed (during ExecutingWorkflowState): cromwell.backend.standard.StandardAsyncExecutionActor$$anon$2: Failed to evaluate job outputs:
Bad output 'CheckContamination.contamination': Failed to read_float("/xxxxxx/cromwell-executions/ExomeGermlineSingleSample/2bfcc03f-928f-48bf-ad4d-ca8816dd6be0/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/5d960841-0433-46e2-b029-1a4f6b63d117/call-CheckContamination/execution/stdout") (reason 1 of 1): Future timed out after [60 seconds]
        at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$handleExecutionSuccess$1(StandardAsyncExecutionActor.scala:990)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

B.W.

**Comment by rsc3** [comment]
Is this still an issue?
