### ISSUE TITLE
difficulty executing ExomeGermlineSingleSample.wdl

### ISSUE THREAD

**Issue by moe1619** [broadinstitute/warp#788]
Hello, I'm having a little trouble executing the ExomeGermlineSingleSample.wdl on a local cluster. The following happens whether I use my json or the test json. Thank you! Output below...

```
warp-ExomeGermlineSingleSample_v3.1.5/pipelines/broad/dna_seq/germline/single_sample/exome$ java -jar -Dsystem.input-read-limits.lines=600000 /PATH/cromwell-33.1.jar run ./ExomeGermlineSingleSample.wdl --inputs ./test_inputs/Scientific/D5327.NA12878.json

[2022-08-03 18:19:19,50] [info] Running with database db.url = jdbc:hsqldb:mem:afaecfe8-8594-446b-a507-1bd90039b1c6;shutdown=false;hsqldb.tx=mvcc
[2022-08-03 18:19:27,41] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2022-08-03 18:19:27,42] [info] [RenameWorkflowOptionsInMetadata] 100%
[2022-08-03 18:19:27,53] [info] Running with database db.url = jdbc:hsqldb:mem:3cb20166-561b-4836-b9c8-b87d68991559;shutdown=false;hsqldb.tx=mvcc
[2022-08-03 18:19:28,03] [info] Slf4jLogger started
[2022-08-03 18:19:28,35] [info] Workflow heartbeat configuration:
{
  "cromwellId" : "cromid-2859c25",
  "heartbeatInterval" : "2 minutes",
  "ttl" : "10 minutes",
  "writeBatchSize" : 10000,
  "writeThreshold" : 10000
}
[2022-08-03 18:19:28,40] [info] Metadata summary refreshing every 2 seconds.
[2022-08-03 18:19:28,44] [info] CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
[2022-08-03 18:19:28,44] [info] KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
[2022-08-03 18:19:28,44] [info] WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
[2022-08-03 18:19:29,31] [info] JobExecutionTokenDispenser - Distribution rate: 50 per 1 seconds.
[2022-08-03 18:19:29,32] [info] SingleWorkflowRunnerActor: Submitting workflow
[2022-08-03 18:19:29,37] [info] Unspecified type (Unspecified version) workflow 564a27ce-97f5-4d8d-aad3-af4cca98cd9f submitted
[2022-08-03 18:19:29,41] [info] SingleWorkflowRunnerActor: Workflow submitted [38;5;2m564a27ce-97f5-4d8d-aad3-af4cca98cd9f[0m
[2022-08-03 18:19:29,42] [info] 1 new workflows fetched
[2022-08-03 18:19:29,42] [info] WorkflowManagerActor Starting workflow [38;5;2m564a27ce-97f5-4d8d-aad3-af4cca98cd9f[0m
[2022-08-03 18:19:29,43] [info] WorkflowManagerActor Successfully started WorkflowActor-564a27ce-97f5-4d8d-aad3-af4cca98cd9f
[2022-08-03 18:19:29,43] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2022-08-03 18:19:29,44] [[38;5;220mwarn[0m] SingleWorkflowRunnerActor: received unexpected message: Done in state RunningSwraData
[2022-08-03 18:19:29,44] [[38;5;220mwarn[0m] Couldn't find a suitable DSN, defaulting to a Noop one.
[2022-08-03 18:19:29,45] [info] Using noop to send events.
[2022-08-03 18:19:29,47] [info] WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
[2022-08-03 18:19:29,51] [info] MaterializeWorkflowDescriptorActor [[38;5;2m564a27ce[0m]: Parsing workflow as WDL 1.0
[2022-08-03 18:19:30,01] [[38;5;1merror[0m] WorkflowManagerActor Workflow 564a27ce-97f5-4d8d-aad3-af4cca98cd9f failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Empty label is not a legal name
java.net.IDN.toASCIIInternal(IDN.java:283)
java.net.IDN.toASCII(IDN.java:122)
java.net.IDN.toASCII(IDN.java:151)
com.softwaremill.sttp.Uri.encodeHost(Uri.scala:171)
com.softwaremill.sttp.Uri.toString(Uri.scala:122)
com.softwaremill.sttp.asynchttpclient.AsyncHttpClientBackend.requestToAsync(AsyncHttpClientBackend.scala:152)
com.softwaremill.sttp.asynchttpclient.AsyncHttpClientBackend.send(AsyncHttpClientBackend.scala:40)
com.softwaremill.sttp.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:15)
com.softwaremill.sttp.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:10)
com.softwaremill.sttp.RequestT.send(RequestT.scala:242)
cromwell.languages.util.ImportResolver$.$anonfun$httpResolverWithHeaders$1(ImportResolver.scala:88)
common.transforms.package$CheckedAtoB$.$anonfun$firstSuccess$2(package.scala:25)
scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
scala.collection.immutable.List.foldLeft(List.scala:86)
common.transforms.package$CheckedAtoB$.$anonfun$firstSuccess$1(package.scala:22)
cats.data.Kleisli.$anonfun$andThen$1(Kleisli.scala:37)
wdl.draft3.transforms.wdlom2wom.FileElementToWomBundle$.wdl$draft3$transforms$wdlom2wom$FileElementToWomBundle$$importWomBundle(FileElementToWomBundle.scala:101)
wdl.draft3.transforms.wdlom2wom.FileElementToWomBundle$$anon$1.$anonfun$toWomBundle$11(FileElementToWomBundle.scala:74)
cats.instances.VectorInstances$$anon$1.$anonfun$traverse$2(vector.scala:77)
cats.instances.VectorInstances$$anon$1.loop$2(vector.scala:40)
cats.instances.VectorInstances$$anon$1.$anonfun$foldRight$2(vector.scala:41)
cats.Eval$.advance(Eval.scala:272)
cats.Eval$.loop$1(Eval.scala:354)
cats.Eval$.cats$Eval$$evaluate(Eval.scala:372)
cats.Eval$Defer.value(Eval.scala:258)
cats.instances.VectorInstances$$anon$1.traverse(vector.scala:76)
cats.instances.VectorInstances$$anon$1.traverse(vector.scala:12)
cats.Traverse$Ops.traverse(Traverse.scala:19)
cats.Traverse$Ops.traverse$(Traverse.scala:19)
cats.Traverse$ToTraverseOps$$anon$3.traverse(Traverse.scala:19)
wdl.draft3.transforms.wdlom2wom.FileElementToWomBundle$$anon$1.toWomBundle(FileElementToWomBundle.scala:74)
wdl.draft3.transforms.wdlom2wom.FileElementToWomBundle$$anon$1.toWomBundle(FileElementToWomBundle.scala:30)
wom.transforms.WomBundleMaker$Ops.toWomBundle(WomExecutableMaker.scala:16)
wom.transforms.WomBundleMaker$Ops.toWomBundle$(WomExecutableMaker.scala:16)
wom.transforms.WomBundleMaker$ops$$anon$2.toWomBundle(WomExecutableMaker.scala:16)
wdl.draft3.transforms.wdlom2wom.FileElementToWomBundle$.convert(FileElementToWomBundle.scala:83)
wdl.draft3.transforms.wdlom2wom.package$.$anonfun$fileElementToWomBundle$1(package.scala:13)
scala.util.Either$RightProjection.flatMap(Either.scala:702)
cats.instances.EitherInstances$$anon$1.flatMap(either.scala:36)
cats.instances.EitherInstances$$anon$1.flatMap(either.scala:32)
cats.data.Kleisli.$anonfun$andThen$1(Kleisli.scala:37)
languages.wdl.draft3.WdlDraft3LanguageFactory.getWomBundle(WdlDraft3LanguageFactory.scala:50)
wdl.draft3.transforms.wdlom2wom.FileElementToWomBundle$.$anonfun$importWomBundle$2(FileElementToWomBundle.scala:93)
common.transforms.package$CheckedAtoB$.$anonfun$firstSuccess$1(package.scala:21)
scala.util.Either$RightProjection.flatMap(Either.scala:702)
cats.instances.EitherInstances$$anon$1.flatMap(either.scala:36)
cats.instances.EitherInstances$$anon$1.flatMap(either.scala:32)
cats.data.Kleisli.$anonfun$andThen$1(Kleisli.scala:37)
wdl.draft3.transforms.wdlom2wom.FileElementToWomBundle$.wdl$draft3$transforms$wdlom2wom$FileElementToWomBundle$$importWomBundle(FileElementToWomBundle.scala:101)
wdl.draft3.transforms.wdlom2wom.FileElementToWomBundle$$anon$1.$anonfun$toWomBundle$11(FileElementToWomBundle.scala:74)
cats.instances.VectorInstances$$anon$1.$anonfun$traverse$2(vector.scala:77)
cats.instances.VectorInstances$$anon$1.loop$2(vector.scala:40)
cats.instances.VectorInstances$$anon$1.$anonfun$foldRight$2(vector.scala:41)
cats.Eval$.advance(Eval.scala:272)
cats.Eval$.loop$1(Eval.scala:354)
cats.Eval$.cats$Eval$$evaluate(Eval.scala:372)
cats.Eval$Defer.value(Eval.scala:258)
cats.instances.VectorInstances$$anon$1.traverse(vector.scala:76)
cats.instances.VectorInstances$$anon$1.traverse(vector.scala:12)
cats.Traverse$Ops.traverse(Traverse.scala:19)
cats.Traverse$Ops.traverse$(Traverse.scala:19)
cats.Traverse$ToTraverseOps$$anon$3.traverse(Traverse.scala:19)
wdl.draft3.transforms.wdlom2wom.FileElementToWomBundle$$anon$1.toWomBundle(FileElementToWomBundle.scala:74)
wdl.draft3.transforms.wdlom2wom.FileElementToWomBundle$$anon$1.toWomBundle(FileElementToWomBundle.scala:30)
wom.transforms.WomBundleMaker$Ops.toWomBundle(WomExecutableMaker.scala:16)
wom.transforms.WomBundleMaker$Ops.toWomBundle$(WomExecutableMaker.scala:16)
wom.transforms.WomBundleMaker$ops$$anon$2.toWomBundle(WomExecutableMaker.scala:16)
wdl.draft3.transforms.wdlom2wom.FileElementToWomBundle$.convert(FileElementToWomBundle.scala:83)
wdl.draft3.transforms.wdlom2wom.package$.$anonfun$fileElementToWomBundle$1(package.scala:13)
scala.util.Either$RightProjection.flatMap(Either.scala:702)
cats.instances.EitherInstances$$anon$1.flatMap(either.scala:36)
cats.instances.EitherInstances$$anon$1.flatMap(either.scala:32)
cats.data.Kleisli.$anonfun$andThen$1(Kleisli.scala:37)
languages.wdl.draft3.WdlDraft3LanguageFactory.getWomBundle(WdlDraft3LanguageFactory.scala:50)
languages.wdl.draft3.WdlDraft3LanguageFactory.$anonfun$validateNamespace$2(WdlDraft3LanguageFactory.scala:39)
scala.util.Either.flatMap(Either.scala:338)
languages.wdl.draft3.WdlDraft3LanguageFactory.validateNamespace(WdlDraft3LanguageFactory.scala:38)
cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.$anonfun$buildWorkflowDescriptor$7(MaterializeWorkflowDescriptorActor.scala:242)
cats.data.EitherT.$anonfun$flatMap$1(EitherT.scala:80)
cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:128)
cats.effect.internals.IORunLoop$.start(IORunLoop.scala:35)
cats.effect.IO.unsafeRunAsync(IO.scala:257)
cats.effect.IO.unsafeToFuture(IO.scala:328)
cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$1.$anonfun$applyOrElse$1(MaterializeWorkflowDescriptorActor.scala:146)
scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:200)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:173)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:165)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.processEvent(FSM.scala:665)
	at akka.actor.FSM.processEvent$(FSM.scala:662)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:123)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:801)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:783)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:123)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:659)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:653)
	at akka.actor.Actor.aroundReceive(Actor.scala:514)
	at akka.actor.Actor.aroundReceive$(Actor.scala:512)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:123)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[2022-08-03 18:19:30,02] [info] WorkflowManagerActor WorkflowActor-564a27ce-97f5-4d8d-aad3-af4cca98cd9f is in a terminal state: WorkflowFailedState
[2022-08-03 18:19:36,17] [info] SingleWorkflowRunnerActor workflow finished with status 'Failed'.
[2022-08-03 18:19:38,44] [info] Workflow polling stopped
[2022-08-03 18:19:38,46] [info] Shutting down WorkflowStoreActor - Timeout = 5 seconds
[2022-08-03 18:19:38,49] [info] Shutting down WorkflowLogCopyRouter - Timeout = 5 seconds
[2022-08-03 18:19:38,49] [info] Shutting down JobExecutionTokenDispenser - Timeout = 5 seconds
[2022-08-03 18:19:38,50] [info] Aborting all running workflows.
[2022-08-03 18:19:38,50] [info] JobExecutionTokenDispenser stopped
[2022-08-03 18:19:38,55] [info] WorkflowLogCopyRouter stopped
[2022-08-03 18:19:38,55] [info] WorkflowStoreActor stopped
[2022-08-03 18:19:38,55] [info] Shutting down WorkflowManagerActor - Timeout = 3600 seconds
[2022-08-03 18:19:38,55] [info] WorkflowManagerActor All workflows finished
[2022-08-03 18:19:38,55] [info] WorkflowManagerActor stopped
[2022-08-03 18:19:38,56] [info] Connection pools shut down
[2022-08-03 18:19:43,57] [info] Shutting down SubWorkflowStoreActor - Timeout = 1800 seconds
[2022-08-03 18:19:43,57] [[38;5;220mwarn[0m] Coordinated shutdown phase [service-stop] timed out after 5000 milliseconds
[2022-08-03 18:19:43,57] [info] Shutting down JobStoreActor - Timeout = 1800 seconds
[2022-08-03 18:19:43,57] [info] SubWorkflowStoreActor stopped
[2022-08-03 18:19:43,57] [info] Shutting down CallCacheWriteActor - Timeout = 1800 seconds
[2022-08-03 18:19:43,57] [info] Shutting down ServiceRegistryActor - Timeout = 1800 seconds
[2022-08-03 18:19:43,57] [info] JobStoreActor stopped
[2022-08-03 18:19:43,57] [info] Shutting down DockerHashActor - Timeout = 1800 seconds
[2022-08-03 18:19:43,57] [info] CallCacheWriteActor Shutting down: 0 queued messages to process
[2022-08-03 18:19:43,57] [info] Shutting down IoProxy - Timeout = 1800 seconds
[2022-08-03 18:19:43,57] [info] CallCacheWriteActor stopped
[2022-08-03 18:19:43,57] [info] WriteMetadataActor Shutting down: 0 queued messages to process
[2022-08-03 18:19:43,57] [info] KvWriteActor Shutting down: 0 queued messages to process
[2022-08-03 18:19:43,57] [info] DockerHashActor stopped
[2022-08-03 18:19:43,58] [info] IoProxy stopped
[2022-08-03 18:19:43,58] [info] ServiceRegistryActor stopped
[2022-08-03 18:19:43,60] [info] Database closed
[2022-08-03 18:19:43,60] [info] Stream materializer shut down
[2022-08-03 18:19:43,65] [info] Automatic shutdown of the async connection
[2022-08-03 18:19:43,65] [info] Gracefully shutdown sentry threads.
[2022-08-03 18:19:43,65] [info] Shutdown finished.
```

**Comment by moe1619** [comment]
Whoops! updated java and Cromwell and now getting past this error. Will re-post a new issue if I continue to have problems. Thanks!
